[pytest]
# 更改测试模块命名规则
;python_files = myTest*
# 更改测试类命名规则
;python_classes = myTest*
# 更改测试方法/测试函数命名规则
;python_functions = myTest*

;python_files = myAssert*
;python_classes = myAssert*
;python_functions = myAssert*
;
;python_files = order*
;python_classes = order*
;python_functions = order*